### ISSUE TITLE
dark/light theme

### ISSUE THREAD

**Issue by ChaituKNag** [ChaituKNag/my-components#2]
## Tasks
- [ ] Create a provider component
- [ ] Create a hook to determine and set the theme
- [ ] Take an option to check if `prefers-color-scheme` is selected and make use of it
- [ ] Write test cases for each of the components
